AWSTemplateFormatVersion: "2010-09-09"

Resources:
  VoicesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tta-voices

  ScriptResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tta-script-results

  SpeechResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tta-speech-results

  TextFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tta-text-files

  JobStatusBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tta-job-status

  FeedbackBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tta-feedback

  ModelFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tta-model-files

  # Need to manually create access keys for the user.
  SpeechServiceUser:
    Type: AWS::IAM::User
    Properties:
      UserName: SpeechServiceUser

  # Need to rename this policy to be more general.
  SpeechServiceIAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: SpeechServiceS3ReadWritePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - !Sub "arn:aws:s3:::${SpeechResultsBucket}/*"
              - !Sub "arn:aws:s3:::${VoicesBucket}/*"
              - !Sub "arn:aws:s3:::${TextFilesBucket}/*"
              - !Sub "arn:aws:s3:::${ScriptResultsBucket}/*"
              - !Sub "arn:aws:s3:::${JobStatusBucket}/*"
              - !Sub "arn:aws:s3:::${FeedbackBucket}/*"
              - !Sub "arn:aws:s3:::${ModelFilesBucket}/*"
              - !Sub "arn:aws:s3:::${SpeechResultsBucket}"
              - !Sub "arn:aws:s3:::${VoicesBucket}"
              - !Sub "arn:aws:s3:::${TextFilesBucket}"
              - !Sub "arn:aws:s3:::${ScriptResultsBucket}"
              - !Sub "arn:aws:s3:::${JobStatusBucket}"
              - !Sub "arn:aws:s3:::${FeedbackBucket}"
              - !Sub "arn:aws:s3:::${ModelFilesBucket}"
      Users:
        - !Ref SpeechServiceUser
