AWSTemplateFormatVersion: "2010-09-09"

Resources:
  VoicesAudiosBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tta-voices-audios

  VoicesMetadataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tta-voices-metadata

  ScriptResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tta-script-results

  SpeechResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tta-speech-results

  TextFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tta-text-files
