[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ttaservice"
version = "0.0.1"
authors = [
  { name="Faizi Fifita", email="author@example.com" },
]
description = "ttaservice (Text-to-Audiobook API service) is the service for interfacing with the tta library."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
  "fastapi==0.115.2",
  "uvicorn==0.32.0",
  "python-multipart==0.0.17",
]

[tool.coverage.run]
source = ["ttaservice"]
omit = []

[project.urls]
Homepage = "https://github.com/FayZ676/audiobook-generator"
Issues = "https://github.com/FayZ676/audiobook-generator/issues"
