[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tta_speech"
version = "0.0.1"
authors = [
  { name="Faizi Fifita", email="author@example.com" },
  { name="Nathan Lane", email="nathanlane510@gmail.com" },
  { name="Derrick Strover", email="dstroverduncan@yahoo.com" },
  { name="Travis Loukusa", email="dl2625pv@go.minnstate.edu" },
]
description = ""
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "f5-tts==1.1.0",
    "fastapi==0.115.2",
    "pydub==0.25.1",
    "torch==2.6.0",
    "torchaudio==2.6.0",
    "uvicorn==0.32.0",
]

[project.urls]
Homepage = "https://github.com/FayZ676/audiobook-generator"
Issues = "https://github.com/FayZ676/audiobook-generator/issues"
