[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tta_aws"
version = "0.0.1"
authors = [
  { name="Faizi Fifita", email="author@example.com" },
]
description = ""
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/FayZ676/audiobook-generator"
