[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tta_script"
version = "0.0.1"
authors = [
  { name="Faizi Fifita", email="author@example.com" },
]
description = "tta (Text-to-Audiobook), as the name suggests, transforms book text in a multi-speaker audiobook experience."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
  "openai==1.61.1",
  "pylint==3.3.1",
  "python-multipart==0.0.17",
  "pytest==8.3.3",
  "pytest-cov==5.0.0",
  "runpod==1.7.9",
  "scikit-learn==1.6.1",
  "spacy==3.8.4",
  "tta_data==0.0.1",
  "tta_types==0.0.1",
]

[tool.coverage.run]
source = ["tta"]
omit = [
    "*/tests/*",
    "tta/models/*",
    "tta/voices.py",
    "tta/narration.py",
]

[project.urls]
Homepage = "https://github.com/FayZ676/audiobook-generator"
Issues = "https://github.com/FayZ676/audiobook-generator/issues"
